---
grails:
    profile: web
    codegen:
        defaultPackage: omp.grails.upgrade
    spring:
        transactionManagement:
            proxies: false
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
    cache:
        ehcache:
            ehcacheXmlLocation: 'classpath:ozone/marketplace/ehcache3.xml'
            lockTimeout: 200  # milliseconds

info:
    app:
        name: "@info.app.name@"
        version: "@info.app.version@"
        grailsVersion: "@info.app.grailsVersion@"

---
security:
    basic:
        enabled: false

---

spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true
        unique-names: true

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false  # true
        use_query_cache: false
#         region.factory_class: "org.hibernate.cache.ehcache.EhCacheRegionFactory"
        # region.factory_class: "org.hibernate.cache.SingletonEhCacheRegionFactory"
#    flush.mode: AUTO

dataSource:
    pooled: true
    jmxExport: true

environments:
    test:
        dataSource:
            dbCreate: create-drop
            url: jdbc:oracle:thin:@localhost:1521/ORCLCDB
            driverClassName: oracle.jdbc.driver.OracleDriver
            username: system
            password: omp

    development:
        dataSource:
            dbCreate: create-drop
            url: jdbc:oracle:thin:@localhost:1521/ORCLCDB
            driverClassName: oracle.jdbc.driver.OracleDriver
            username: system
            password: omp
            properties:
                minEvictableIdleTimeMillis: 30000
                timeBetweenEvictionRunsMillis: 5000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                validationQuery: "SELECT 1 FROM DUAL"
                validationInterval: 30000
                maxActive: 100
                initialSize: 10
                maxIdle: 50
                minIdle: 10
                removeAbandoned: true
                removeAbandonedTimeout: 60
                abandonWhenPercentageFull: 50
                jdbcInterceptors: "ResetAbandonedTimer"

    production:
        dataSource:
            dbCreate: update
            url: jdbc:oracle:thin:@localhost:1521/ORCLCDB
            driverClassName: oracle.jdbc.driver.OracleDriver
            username: system
            password: omp
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1 FROM DUAL
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED

---
grails:
    urlmapping:
        cache:
            maxsize: 1000

    controllers:
        defaultScope: singleton

    converters:
        encoding: UTF-8

    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: "*/*"
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml

# Migrated from application.groovy
---
marketplace:
    layout: "marketplace"
    defaultAffiliatedMarketplaceTimeout: 30000
    defaultSearchPageSize: 24
    defaultLandingPageSize: 18

notifications:
    enabled: false


grails:
    cache:
        enabled: false

    mime:
        file:
            extensions: false

    views:
        default:
            codec: "none"

    databinding:
        useSpringBinder: true

    enable:
        # enabled native2ascii conversion of i18n properties files
        native2ascii: true

httpsession.timeout: 120

system_user_id: 1

discoveryMaxPerRow: 5
discoveryWidgetMaxPerRow: 6

---
grails.plugin.databasemigration:
    changelogFileName: "changelog_master.groovy"
    updateOnStart: false
    updateOnStartFileNames:
      - "changelog_master.groovy"

---
org.grails.plugins.jaxrs:
    doreader.disable: true
    dowriter.disable: true

org.grails.jaxrs.enabled: false

---
cef:
    device:
        vendor: "OZONE"
        product: "Store"
        version: "500-27_L2::1.3"
    version: 0

---
elasticSearch:
    datastoreImpl: "hibernateDatastore"
    client:
        mode: "local"
    unmarshallComponents: true
environments:
    test:
        elasticSearch:
            client:
                mode: "local"
            index:
                store:
                    type: "fs"

    production:
        elasticSearch:
            client:
                mode: "local"

---
quartz:
    autoStartup: false
    props:
        scheduler.skipUpdateCheck: true

environments:
    production:
        quartz:
            autoStartup: true
            props:
                scheduler.skipUpdateCheck: true

# Migrated from OverlayConfig.groovy
---
is:
    franchise:
        store: true

---
store:
    is:
        franchise: true

# Migrated from MetadataConfig.groovy
---
marketplace:
    metadata:
        profiles:
          - username: "testAdmin1"
            displayName: "testAdmin1"
            password: "password"

        types:
          - title: "Web App"
            imageFilename: "default_types_web_apps_icon.png"
            description: "web app"
            ozoneAware: false
            hasLaunchUrl: true
            hasIcons: false
            isPermanent: false
          - title: "App Component"
            imageFilename: "default_types_widget_icon.png"
            description: "app component"
            ozoneAware: true
            hasLaunchUrl: true
            hasIcons: true
            isPermanent: true
          - title: "OZONE App"
            imageFilename: "default_types_stack_icon.png"
            description: "OZONE app"
            ozoneAware: true
            hasLaunchUrl: false
            hasIcons: false
            isPermanent: true

        rejectionJustifications:
          - title: "Sustainment"
            description: "Sustainment"
          - title: "Security Guideline"
            description: "Security Guideline"
          - title: "Data Content"
            description: "Data Content"
          - title: "Not Operational"
            description: "Not Operational"
          - title: "Lack of Documentation"
            description: "Lack of Documentation"

        states:
          - title: "Active"
            description: "Active description"
            isPublished: true
          - title: "Beta"
            description: "Beta description"
            isPublished: false
          - title: "Deprecated"
            description: "Deprecated description"
            isPublished: false
          - title: "Planned"
            description: "Planned description"
            isPublished: false
          - title: "Retired"
            description: "Retired description"
            isPublished: false

        owfWidgetTypes:
          - title: "standard"
            description: "Widget will appear in OWF's Launch Menu"
          - title: "metric"
            description: "Widget will appear under the Metric button on OWF's toolbar"
          - title: "marketplace"
            description: "Widget will appear under the Marketplace button on OWF's toolbar"
          - title: "administration"
            description: "Widget will appear under the Administration button on OWF's toolbar"

        intentDataTypes:
          - title: "audio"
            description: "Audio file. SAMPLE DATA TYPE."
          - title: "image"
            description: "Image file. SAMPLE DATA TYPE."
          - title: "json"
            description: "JSON document. SAMPLE DATA TYPE."
          - title: "text"
            description: "Textual information. SAMPLE DATA TYPE."
          - title: "uri"
            description: "URI - Uniform Resource Identifier. SAMPLE DATA TYPE."
          - title: "video"
            description: "Video file. SAMPLE DATA TYPE."

        intentActions:
          - title: "share"
            description: "The share intent is designed to give applications the ability to offer a simple mechanism for sharing data from the current page."
          - title: "edit"
            description: "The edit intent is designed to give applications the ability to offer a simple mechanism to edit data from the current page."
          - title: "view"
            description: "The view intent is designed to give applications the ability to offer a simple mechanism to view data in their application."
          - title: "pick"
            description: "The pick intent is designed to give services the ability to allow their users pick files from their service for use in a client application."
          - title: "subscribe"
            description: "The subscribe intent is designed to give applications the ability to offer a simple mechanism for subscribing to data from the current page"
          - title: "save"
            description: "The Save intent is designed to give applications the ability to offer a simple mechanism to save data in their application."
